name: CI

on: [push]

jobs:
  build_mac_zip:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create temp folder
      run: |
        sudo mkdir -p /dist/sqlbear_mac_x64
    - name: Copy to temp folder
      run: |
        sudo cp -Rf ./* /dist/sqlbear_mac_x64
    - name: Download Mac jre
      run: |
        wget https://github.com/AdoptOpenJDK/openjdk13-binaries/releases/download/jdk-13%2B33/OpenJDK13U-jre_x64_mac_hotspot_13_33.tar.gz
        tar -xf OpenJDK13U-jre_x64_mac_hotspot_13_33.tar.gz
        sudo cp -r ./jdk-13+33-jre/Contents/Home /dist/sqlbear_mac_x64/jre/
    - name: Archive zip
      uses: actions/upload-artifact@v1
      with:
        name: sqlbear_mac_x64
        path: /dist/sqlbear_mac_x64
