name: CI

on: [push]

jobs:
  build_mac_zip:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create temp folder
      env:
        target: sqlbear_mac_x64
      run: |
        sh ./build_mac_zip.sh
    - name: Archive zip
      uses: actions/upload-artifact@v1
      with:
        name: sqlbear_mac_x64
        path: /dist/sqlbear_mac_x64
